### ISSUE TITLE
isn't show in fontlist of jetbrains ide

### ISSUE THREAD

**Issue by nsnail** [githubnext/monaspace#20]
![image](https://github.com/githubnext/monaspace/assets/1327344/3413d5e6-fe9e-4e8f-a4e2-6d1e772ef153)

**Comment by nsnail** [comment]
i confirm that has been installed in the windows
![image](https://github.com/githubnext/monaspace/assets/1327344/d4618b36-f3cd-40bd-aeca-8e24c93f0cd4)

**Comment by bmarwell** [comment]
1. Search for "Krypton" and "Neon" etc. instead
2. Fully close IntelliJ, make sure all processes are terminated for a few seconds before you re-start IntelliJ

**Comment by Ayesh** [comment]
@bmarwell didn't work, unfortunately. I think the Monospace bit is missing in the fonts, so the IDE does not detect them as monospace fonts. They show up in Microsoft Word, for example.

**Comment by maniel** [comment]
many programs don't see it as a monospaced fonts, for example in putty or windows terminal i have to explicitly enable usage of non-monospaced fonts, windows terminal even issues a warning about possible incompatibilities when using non-monospaced font in terminal

**Comment by bmarwell** [comment]
I can confirm it shows up in IntelliJ on Mac and on Linux. It's not a font issue.

**Comment by Carighan** [comment]
> I can confirm it shows up in IntelliJ on Mac and on Linux. It's not a font issue.

It does not for me, **when using the variable files**. If I use the static ones, those *do* show up, but only Xenon renders at all, and even that doesn't render correctly.

**Comment by KiligFei** [comment]
Yes, vscode Settings do not work on windows computers either

**Comment by NanaVan** [comment]
Also, gVim in Windows setting can not detect them as monospace fonts.

**Comment by Xp0s3d** [comment]
After installing them they initially also didn't show up in IntelliJ. After some digging around I found out you need to use "Install for all users" instead of "Install". 
![image](https://github.com/githubnext/monaspace/assets/41455536/eb2019fa-70e0-4ed5-8663-723a15c3cd67)

After installing them again using that option they did indeed show up in my IntelliJ
![image](https://github.com/githubnext/monaspace/assets/41455536/9109f885-caf6-4601-86b5-e2bf536f5af2)

**Comment by moritz-john** [comment]
Same problem in KDE Konsole: you have to check the "Show all fonts" checkbox first, which shows you all "non monospaced" fonts. 
Some kind of "monospace flag" seems to missing in Monaspace.

![2023-11-10_12-24](https://github.com/githubnext/monaspace/assets/70295002/b1410c6c-7a94-4fa8-888d-b637dc68f8c0)

**Comment by aardvark** [comment]
I can reconfirm that in IntelliJ font only appear after you do "Install for all users" (exactly like reported by @Xp0s3d) 
This really should not be required for fonts to work. I have installed multiple fonts for IntelliJ and this is first font that I need to "Install for all users" for it to work. Something really don't work as it should.

**Comment by nsnail** [comment]
Thanks for all . The issue has been resolved with the following steps: 1. When installing the font, choose "Install for all users." 2. Restart the IDE. 3. When selecting the font in IDE, uncheck "Show only monospaced fonts"

**Comment by Tnze** [comment]
> After installing them they initially also didn't show up in IntelliJ. After some digging around I found out you need to use "Install for all users" instead of "Install"

@Xp0s3d Thanks, it works.

**Comment by smlombardi** [comment]
This made them show up, but ligatures couldn't be activated

**Comment by NightFurySL2001** [comment]
For JetBrains IDEA, it seems that either all 4 variants (regular-bold-italic-bold italic) or only the regular weight should be present for the font to be considered as "monospaced", which is a weird move considering some monospaced fonts doesn't have bold or italic.

Source: https://stackoverflow.com/questions/43178286/how-does-a-font-tell-the-os-that-i-am-a-monspaced-fixed-width-font

**Comment by Konijnebeer** [comment]
Hi, for me It still does not show up within the IDE (PhPstorm), I downloaded all 4 types as the message above sugested, it does not even show up as a non monospace font. It can find all other fonts on my system but not Monaspace fonts.
I also don't get the option to install for all users (I'm the only user on the system0

**Comment by idan** [comment]
OK, v1.2 was merged in #273, and that includes the new `frozen` format files which bake in the typographical features for environments which do not give you the typographical controls to enable the various OpenType features, like the various JetBrains IDEs.

It sounds like maybe we ought to also add a note to the README that fonts must be installed for all users in order to be picked up by JetBrains IDEs.

**Comment by SpareSimian** [comment]
What must applications do to use Texture Healing? Editors like Gnu Emacs, Vim, Lugaru Epsilon, etc. Terminals like PuTTY, the Linux console, Windows Terminal, Powershell, and cmd.exe. Frameworks like QT and wxWidgets.

**Comment by Tnze** [comment]
> What must applications do to use Texture Healing? Editors like Gnu Emacs, Vim, Lugaru Epsilon, etc. Terminals like PuTTY, the Linux console, Windows Terminal, Powershell, and cmd.exe. Frameworks like QT and wxWidgets.

The application which rendering text is the concern one. Thus, the terminal or editor, not the shell. It doesn't matter you're using powershell or cmd or bash or zsh or whatever.
